In [1]:
%load_ext autoreload
%autoreload 2

In [29]:
import torch
import torch.nn as nn

# Define the input tensors
input1 = torch.randn(3, 5)  # Example input tensor 1
input2 = torch.randn(3, 5)  # Example input tensor 2

# Create targets indicating whether inputs should be treated as similar or dissimilar
target = torch.tensor([1, -1, 1])  # 1 indicates similar, -1 indicates dissimilar

# Instantiate the CosineEmbeddingLoss with a margin of 0.5
cosine_embedding_loss = nn.CosineEmbeddingLoss()

# Compute the cosine embedding loss
loss = cosine_embedding_loss(input1, input2, target)

print("Cosine Embedding Loss:", loss.item())

Cosine Embedding Loss: 0.9444395899772644


In [3]:
input1

tensor([[ 0.2240, -0.5727,  0.0808, -0.9831,  1.3873],
        [-0.7965, -0.7258,  2.7778,  0.5067,  0.5167],
        [ 0.1874,  0.7030,  0.0727,  1.3244,  1.0403]])

In [4]:
input2

tensor([[-0.2212, -0.4836,  0.1282, -1.4081, -1.2179],
        [-0.0232,  0.8852, -2.2533,  1.0012, -0.9905],
        [ 0.9087, -0.0981, -0.9945,  1.1325, -0.3098]])

In [6]:
torch.tensor([[ 0.2240, -0.5727,  0.0808, -0.9831,  1.3873],
        [-0.7965, -0.7258,  2.7778,  0.5067,  0.5167],
        [ 0.1874,  0.7030,  0.0727,  1.3244,  1.0403]])

tensor([[ 0.2240, -0.5727,  0.0808, -0.9831,  1.3873],
        [-0.7965, -0.7258,  2.7778,  0.5067,  0.5167],
        [ 0.1874,  0.7030,  0.0727,  1.3244,  1.0403]])

In [40]:
input1 = torch.tensor([[1, 2, 3]])

In [41]:
input2 = torch.tensor([[1, 2, 3]])

In [42]:
target =torch.tensor([-1])

In [43]:
cosine_embedding_loss(input1, input2, target).item()

1.0

In [45]:
import numpy as np
use_all_range= np.random.randint(0,2)

In [46]:
use_all_range

0

In [47]:
if use_all_range==1:
    'equal
    '

SyntaxError: unterminated string literal (detected at line 2) (2107613814.py, line 2)